spring.application.name=notifications-service


spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.kafka.bootstrap-servers=localhost:9092
spring.datasource.url=jdbc:postgresql://localhost:5433/notification_db
logging.level.com.zaxxer.hikari=DEBUG

app.kafka.topic.notification=notification-topic